CREATE SCHEMA IF NOT EXISTS moderation;

CREATE TABLE IF NOT EXISTS moderation.reason (
    code text PRIMARY KEY,
    label text NOT NULL,
    policy_area text NOT NULL,
    policy_reference text,
    active boolean DEFAULT true NOT NULL,
    sort_order smallint DEFAULT 0 NOT NULL
);

INSERT INTO moderation.reason (code, label, policy_area, policy_reference, sort_order)
VALUES
    ('harassment_or_abuse', 'Harassment or abuse', 'terms', NULL, 10),
    ('personal_or_sensitive_info', 'Personal or sensitive information', 'privacy', NULL, 20),
    ('spam_or_manipulation', 'Spam or manipulation', 'terms', NULL, 30),
    ('irrelevant_or_low_quality', 'Irrelevant or low-quality content', 'terms', NULL, 40),
    ('false_or_misleading', 'False or misleading content', 'terms', NULL, 50),
    ('unsafe_or_explicit_media', 'Unsafe or explicit media', 'safety', NULL, 60),
    ('copyright_or_file_policy', 'Copyright or file policy', 'terms', NULL, 70),
    ('academic_integrity', 'Academic integrity', 'terms', NULL, 80),
    ('privacy_request', 'Privacy request', 'privacy', NULL, 90),
    ('other', 'Other', 'other', NULL, 100)
ON CONFLICT (code) DO UPDATE
SET
    label = EXCLUDED.label,
    policy_area = EXCLUDED.policy_area,
    policy_reference = EXCLUDED.policy_reference,
    active = true,
    sort_order = EXCLUDED.sort_order;

CREATE TABLE IF NOT EXISTS moderation.action_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id bigint REFERENCES account."user"(id) ON DELETE SET NULL,
    target_type text NOT NULL,
    target_id text NOT NULL,
    action text NOT NULL,
    reason_code text REFERENCES moderation.reason(code) ON UPDATE CASCADE,
    note text,
    previous_state jsonb,
    next_state jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT moderation_action_log_target_type_check
        CHECK (target_type IN (
            'professor_review',
            'review_reply',
            'review_attachment',
            'review_report',
            'course_file',
            'professor_request',
            'professor'
        )),
    CONSTRAINT moderation_action_log_action_check
        CHECK (action IN (
            'approve',
            'reject',
            'hide',
            'restore',
            'dismiss',
            'resolve',
            'mark_duplicate',
            'note'
        ))
);

CREATE TABLE IF NOT EXISTS moderation.signal (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type text NOT NULL,
    target_id text NOT NULL,
    source text NOT NULL,
    attribute text NOT NULL,
    score double precision,
    threshold double precision,
    severity text,
    payload jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT moderation_signal_target_type_check
        CHECK (target_type IN (
            'professor_review',
            'review_reply',
            'review_attachment',
            'review_report',
            'course_file',
            'professor_request',
            'professor'
        ))
);

ALTER TABLE professor.review
    ADD COLUMN IF NOT EXISTS reviewed_at timestamp with time zone,
    ADD COLUMN IF NOT EXISTS reviewer_user_id bigint REFERENCES account."user"(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS moderation_reason_code text REFERENCES moderation.reason(code) ON UPDATE CASCADE,
    ADD COLUMN IF NOT EXISTS moderation_note text;

ALTER TABLE professor.review_reply
    ADD COLUMN IF NOT EXISTS reviewed boolean DEFAULT false NOT NULL,
    ADD COLUMN IF NOT EXISTS reviewed_at timestamp with time zone,
    ADD COLUMN IF NOT EXISTS reviewer_user_id bigint REFERENCES account."user"(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS moderation_reason_code text REFERENCES moderation.reason(code) ON UPDATE CASCADE,
    ADD COLUMN IF NOT EXISTS moderation_note text;

ALTER TABLE professor.review_attachment
    ADD COLUMN IF NOT EXISTS reviewed boolean DEFAULT false NOT NULL,
    ADD COLUMN IF NOT EXISTS reviewed_at timestamp with time zone,
    ADD COLUMN IF NOT EXISTS reviewer_user_id bigint REFERENCES account."user"(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS moderation_reason_code text REFERENCES moderation.reason(code) ON UPDATE CASCADE,
    ADD COLUMN IF NOT EXISTS moderation_note text;

ALTER TABLE course.file
    ADD COLUMN IF NOT EXISTS reviewer_user_id bigint REFERENCES account."user"(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS moderation_reason_code text REFERENCES moderation.reason(code) ON UPDATE CASCADE,
    ADD COLUMN IF NOT EXISTS moderation_note text;

ALTER TABLE professor.professor_request
    ADD COLUMN IF NOT EXISTS moderation_reason_code text REFERENCES moderation.reason(code) ON UPDATE CASCADE,
    ADD COLUMN IF NOT EXISTS moderation_note text;

ALTER TABLE professor.professor
    ADD COLUMN IF NOT EXISTS moderated_at timestamp with time zone,
    ADD COLUMN IF NOT EXISTS moderator_user_id bigint REFERENCES account."user"(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS moderation_reason_code text REFERENCES moderation.reason(code) ON UPDATE CASCADE,
    ADD COLUMN IF NOT EXISTS moderation_note text;

ALTER TABLE professor.review_report
    ADD COLUMN IF NOT EXISTS user_id bigint REFERENCES account."user"(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS resolved_at timestamp with time zone,
    ADD COLUMN IF NOT EXISTS resolver_user_id bigint REFERENCES account."user"(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS resolution_action text,
    ADD COLUMN IF NOT EXISTS resolution_reason_code text REFERENCES moderation.reason(code) ON UPDATE CASCADE,
    ADD COLUMN IF NOT EXISTS resolution_note text;

CREATE INDEX IF NOT EXISTS moderation_action_log_target_created_at_index
    ON moderation.action_log (target_type, target_id, created_at DESC);

CREATE INDEX IF NOT EXISTS moderation_signal_target_created_at_index
    ON moderation.signal (target_type, target_id, created_at DESC);

CREATE INDEX IF NOT EXISTS review_moderation_queue_index
    ON professor.review (reviewed, visible, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS review_reply_moderation_queue_index
    ON professor.review_reply (reviewed, visible, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS review_report_open_created_at_index
    ON professor.review_report (resolved, created_at DESC);
