name: 'Check Frontend PR'

on:
  pull_request:
    paths:
      - 'admin-client/**'
      - 'web-client/**'

jobs:
  build-and-test:
    runs-on: 'ubuntu-latest'

    strategy:
      fail-fast: false
      matrix:
        client:
          - 'admin-client'
          - 'web-client'

    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v4'

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v4'
        with:
          node-version: '22.18.0'

      - name: 'Install dependencies'
        run: npm install --no-package-lock --no-audit --no-fund
        working-directory: '${{ matrix.client }}'

      - name: 'Build Vite app (Dry Run)'
        run: npm run build
        working-directory: '${{ matrix.client }}'
